# Generated by Django 4.2.2 on 2023-07-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_status_task_status_remove_task_doer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='doer',
            new_name='executor',
        ),
    ]
