# Generated by Django 4.2.4 on 2023-08-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
