# Generated by Django 4.2.4 on 2023-08-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='self_tasks',
        ),
    ]
