# Generated by Django 4.2.4 on 2023-08-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_owner_task_self_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='self_tasks',
        ),
    ]
