# Generated by Django 4.2.4 on 2023-08-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_task_self_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
    ]
