# Generated by Django 4.2.4 on 2023-09-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_author_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
